baseURL = 'https://szymon-derlecki.github.io/'
theme = 'hugo-coder'
defaultContentLanguage = 'pl'

[languages.pl]
  languageName = "🇵🇱"
  title = "Szymon Derlecki"
  weight = 1
  contentDir = "content/pl"  
  [languages.pl.params]
    author = "Szymon Derlecki"
    info = "Deep Learning / Computer Vision / Signal Processing"
    description = "Portfolio"

  [[languages.pl.menu.main]]
    name = "O mnie"
    url = "about/"
    weight = 1
  [[languages.pl.menu.main]]
    name = "Portfolio"
    url = "posts/"
    weight = 2
  [[languages.pl.menu.main]]
    name = "Kontakt"
    url = "contact/"
    weight = 3

[languages.en]
  languageName = "🇬🇧"
  title = "Szymon Derlecki"
  weight = 2
  contentDir = "content/en"  
  [languages.en.params]
    author = "Szymon Derlecki"
    info = "Deep Learning / Computer Vision / Signal Processing"
    description = "Portfolio"

  [[languages.en.menu.main]]
  name = "About"
  url = "/en/about/"
  weight = 1
  [[languages.en.menu.main]]
    name = "Portfolio"
    url = "/en/posts/"
    weight = 2
  [[languages.en.menu.main]]
    name = "Contact"
    url = "/en/contact/"
    weight = 3

[params]
  avatarURL = "images/image_szymon.jpg"
  customCSS = ["css/custom.css"]
  
  # Kolorowanie składni
  pygmentsStyle = "monokai"
  pygmentsCodeFences = true
  
  # --- DODANE: Natywna obsługa trybów ---
  # "auto" sprawia, że strona dostosuje się do systemu usera, 
  # ale doda też ikonkę księżyca/słońca w menu do ręcznego przełączania.
  colorScheme = "auto" 
  hideColorSchemeToggle = false